### ISSUE TITLE
Application Launchers

### ISSUE THREAD

**Issue by ghost** [jmc-88/tint3#2]
Hi,
I've tried adding launchers section and changing panel_items to LTSBC in the config file, same as possible with tint2-svn, but it doesn't work. Is there a chance you consider supporting this in the future? 
Thanks.

**Comment by jmc-88** [comment]
Yes, I've already dropped tint2conf from my repository, in order to focus on the panel itself. I'd like to keep things stable first - so I'd like to have a binary that doesn't crash or leak memory.

Once that's covered, I'll go through the things that I might have broken and restore those additional features.

**Comment by ghost** [comment]
Okay, that's good to know. :+1:

**Comment by jmc-88** [comment]
I've just tried using some launchers against the latest refactoring HEAD (ce22101c647902542f66dfb288450aeb2ac5cc72) and launchers seem to work just fine. I'll mark it as fixed for now, so please reopen it if it still doesn't work for you.
