### ISSUE TITLE
Check for xsettings-client fails

### ISSUE THREAD

**Issue by Lartza** [jmc-88/tint3#40]
Again another build failure on Arch, after a long while.

This is the current failing PKGBUILD and I don't really know what more to try
https://gist.github.com/Lartza/4f91a4995827fdde488fc7cd3beb7bfa

[CMakeError.log](https://github.com/jmc-88/tint3/files/2342268/CMakeError.log)
[CMakeOutput.log](https://github.com/jmc-88/tint3/files/2342269/CMakeOutput.log)

```
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_LIBCXX
-- Performing Test HAS_LIBCXX - Failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.5.3")
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.42.3
-- Checking for module 'pango'
--   Found pango, version 1.42.3
-- Checking for modules 'cairo;cairo-xlib'
--   Found cairo, version 1.15.12
--   Found cairo-xlib, version 1.15.12
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.56.2
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.56.2
-- Checking for module 'imlib2>=1.4.2'
--   Found imlib2, version 1.5.1
-- Checking for module 'libxsettings-client'
--   Package 'libxsettings-client', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:436 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:602 (_pkg_check_modules_internal)
  CMakeLists.txt:39 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/lartza/aur/tint3-cpp-git/src/tint3/CMakeFiles/CMakeOutput.log".
See also "/home/lartza/aur/tint3-cpp-git/src/tint3/CMakeFiles/CMakeError.log".
```

**Comment by Lartza** [comment]
The libc++ error might be something to note too? It shouldn't prevent build but I have libc++ installed and stdlib still fails for some reason

**Comment by jmc-88** [comment]
This appears to be because the `libxsettings-client-dev` package shipped in Debian-based distributions (which I'm developing on) ships with an appropriate `libxsettings-client.pc` file for pkg-config, whereas this is currently missing from the Arch Linux package:

- https://packages.debian.org/stretch/amd64/libxsettings-client-dev/filelist
- https://www.archlinux.org/packages/community/x86_64/xsettings-client/

It might be a Debian-only change as I can't find the relevant file upstream. I'll see if I can work around that. :(

As for the libc++ error: it is "normal" when using GCC. The relevant command line flag is only exposed by Clang at the moment, and linking against libc++ from GCC requires additional [tweaking of compiler options](https://libcxx.llvm.org/docs/UsingLibcxx.html#using-libc-with-gcc) which is not currently done in tint3's CMakeFiles.txt. I might add that as well but as you noted it's not a blocker.

**Comment by jmc-88** [comment]
@Lartza: as of 846018c1c8ad515abf8924c697e7b778614c1600 the reported issue should be fixed. It compiles cleanly for me in an Arch chroot. Can you check all works as expected on your end too?

Meanwhile I'll see if I can scratch the GCC + libc++ itch.

**Comment by Lartza** [comment]
Built fine for me too, pushed to AUR :)
Keep the issue open as reference to GCC + libc++ at your discretion

**Comment by jmc-88** [comment]
Thanks! I think I have the libc++ linking mostly fixed under GCC too, I'll close this ticket when I push that one out too.

**Comment by jmc-88** [comment]
Pushed, compiles cleanly locally and on Travis CI. There's some improvements that could be done on dynamically finding the libc++ include prefix instead of hardcoding it, but this should be enough in most cases, so I'll defer that to once it becomes necessary.
Marking this one fixed.
