### ISSUE TITLE
Battery icon for system tray not showing

### ISSUE THREAD

**Issue by mcfadzgit** [jmc-88/tint3#8]
Using package 'tint3-cpp-git-r748.cb79110-1-x86_64.pkg.tar.xz' on an Asus Eee PC 1015PX netbook running fully updated Arch Linux. Have enabled (battery = 1) in tint3rc, but the battery icon and its text are not showing in the system tray. (This netbook uses BAT0.)

**Comment by jmc-88** [comment]
It's not showing, ever? Mind that there's an option for hiding the battery if the charge level is above a certain percentage (`battery_hide`, https://github.com/jmc-88/tint3/blob/b52868e3245c75cd098eb076b80d27ceaef92846/src/config.cc#L344), so that might affect it.

**Comment by mcfadzgit** [comment]
No, doesn't ever seem to appear, even though the Battery section was copied exactly from tint2rc which still works fine - battery icon and numbers show as they should with Tint2 on the same netbook.
Here's the tint3rc (=tint2rc) section I am using:

battery = 1
battery_low_status = 20
battery_low_cmd = notify-send -u critical "Danger: battery low"
battery_hide = 0
bat1_font = Liberation Sans Bold 9
bat2_font = Liberation Sans 9
battery_font_color = #FFFFFF 100
battery_padding = 1 1
battery_background_id = 1

Also, I compiled Tint3 with the -DCMAKE_BUILD_TYPE=Debug parameter and checked the redirected error output, console and tint3.dbg file. None seem to show anything regarding the battery.

**Comment by jmc-88** [comment]
No, unfortunately I think there's not many debug prints in place for the battery code. As long as the battery information is correctly reported through /sys/class/power_supply/BAT${N}, this information should be available to tint3... will check more carefully.

**Comment by mcfadzgit** [comment]
Okay, thanks - will wait to see if you turn up anything.
By the way, I've added another comment regarding the earlier bug re Qt5, but I'm afraid I didn't see how to reopen the issue.

**Comment by jmc-88** [comment]
You have a `panel_items` line in your `tint3rc`, which happens to have priority over the rest (because that's what the old code did, and there is a lot of confusion over what the code should consider like a "new config file" or not, and the reasons for this are probably lost in the mists of time).
Not sure why tint2 v0.11 enables it anyway - as it shouldn't, judging by a quick look to the code -, but I guess you can just remove the `panel_items` and enable items in the right order, or alternatively make sure the `panel_items` line is what you intend it to be. Can you try that and see if my claim is correct?

**Comment by mcfadzgit** [comment]
Daniele - I am so sorry to have wasted your time on this non-bug, I found I had `panel_items = LTSC` instead of `panel_items = LTSBC` in my tint3rc on the netbook. Changed and now working as expected. What had happened was that I had rsync'd some files from my desktop to netbook and, of course, the battery option wasn't needed on the desktop system.

But there was an interesting overlap with the other 'icon duplication' bug!
What I did on the netbook was only:
- powered up and logged on
- edited and saved tint3rc using Mouspad
- issued `killall -SIGUSR1 tint3`
- and the battery icon appeared, but _the pasystray icon got duplicated_ !
  (all well now after issuing another `killall -SIGUSR1 tint3`)

So it looks as though it can happen regardless of qpdfview being run.
I know this 'duplicated icon' problem happened with tint2 as well, but never pinned down when/how it happened. Tint3 may well be innocent, and it's something systemic coming from tint2 maybe?

**Comment by jmc-88** [comment]
Might as well be... There's probably something wrong in the system tray handling logic, which is hard to pinpoint. As stated in the README, one of the long-term goals is to use XCB instead of Xlib, a transition which will most likely require rewriting of large chunks of code, including the systray handling (and I will hopefully fix the broken code at that point). If this is not a major issue, I'd like to ignore it for now and possibly have a proper fix later.

**Comment by mcfadzgit** [comment]
Yes - that sounds very sensible and it is not a show-stopper of an issue. So I will close issues and simply issue `killall -SIGUSR1 tint3` if I get offended by the sight of a duplicated icon!
Many thanks for your help.
